apiVersion: v1
kind: Service
metadata:
  name: prometheus-loadbalancer
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
