# deploymentName: deployment-ip-reverse
# replicaCount: 2
# image:
#   repository: ebenezery/ip-reverser
#   pullPolicy: Always
#   tag: "latest"

# service:
#   name: ip-reverser
#   type: LoadBalancer
#   port: 80
#   targetPort: 8000

# resources:
#   limits:
#     cpu: 500m
#     memory: 512Mi
#   requests:
#     cpu: 250m
#     memory: 256Mi

replicas: 2

appName: ip-reverser

port: 8000

configmap:
  name: ip-reverser-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: ebenezery/ip-reverser
  tag: latest
