replicaCount: 2

image:
  repository: ebenezery/ip-reverser
  pullPolicy: IfNotPresent
  tag: "reverserapp-latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Environment variables
env:
  - name: ENVIRONMENT
    value: "staging"
