apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: ip-reverser
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ip-reverser
  template:
    metadata:
      labels:
        app: ip-reverser
    spec:
      containers:
        - name: ip-reverser-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          



